from enum import Enum

class ErrorCode(Enum):
    SUCCESS = 0
    USER_EXISTS = 1
    USER_NOT_FOUND = 2
    INVALID_PASSWORD = 3
    INCORRECT_PASSWORD = 4
    INVALID_USERNAME = 5
    ONLY_ACCEPT_FOLDER = 6
    DUPLICATE_NAME = 7
    ALREADY_SHARED = 8
    DELETE_NONE_EXIST_NODE = 9
    INVALID_PATH = 10
    NODE_NOT_FOUND = 11
    DELETE_ROOT_DIRECTORY = 12
    SHARE_ROOT = 13
    INVALID_REQUEST = 14
    ADD_CHILD_TO_FILE_NODE = 15
    IPFS_ERROR = 16
    EXCEED_MAX_FILE_SIZE = 17
    FILE_NOT_FOUND = 18
    NOT_LOGGED_IN = 19
    UNKNOWN_ERROR = 99
